YoExisto\ContenidoBundle\Entity\Area:
    type:  entity
    table: area
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        nombre:
            type: string
            nullable: false

        descripcion:
            type: text
            nullable: true

    manyToOne:
        municipio:
            targetEntity: YoExisto\ContenidoBundle\Entity\Municipio
            inversedBy: areas
            joinColumn:
                name: municipio_id
                referencedColumnName: id