YoExisto\ContenidoBundle\Entity\Control:
    type:  entity
    table: control
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        usuario:
            type: string
            nullable: false

        descripcion:
            type: text
            nullable: true

        estado:
            type: integer
            nullable: false
        positivos:
            type: integer
            nullable: false
        negativos:
            type: integer
            nullable: false

        created_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update



    manyToOne:
        donde:
            targetEntity: Donde
            joinColumn:
                name: donde_id
                referencedColumnName: id
            cascade: ["persist"]

        que:
            targetEntity: Que
            joinColumn:
                name: que_id
                referencedColumnName: id
            cascade: ["persist"]


    manyToMany:
        votos:
            targetEntity: Voto
            joinTable:
                name: votos_control
                joinColumns:
                    votos_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    control_id:
                        referencedColumnName: id
                        unique: true


