YoExisto\ContenidoBundle\Entity\Voto:
    type:  entity
    table: voto
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        usuario:
            type: string
            nullable: false

        valor:
            type: integer
            nullable: false

