yo_existo_contenido_homepage:
    path:     /hello/{name}
    defaults: { _controller: YoExistoContenidoBundle:Default:index }

yoexisto_login:
    path:      /login
    defaults:  { _controller: YoExistoContenidoBundle:Default:login }

yoexisto_registrar:
    path:      /registrar
    defaults:  { _controller: YoExistoContenidoBundle:Default:registrar }

yoexisto_ready:
    path:      /ready
    defaults:  { _controller: YoExistoContenidoBundle:Default:ready }




#filtros de busqueda
yoexisto_buscar_areas:
    path:      /getAreas/{municipio}
    defaults:  { _controller: YoExistoContenidoBundle:Filtro:getAreaPorMunicipio }
    options:
        expose: true

yoexisto_buscar_actividad_por_area:
    path:      /getActividadPorArea/{area}
    defaults:  { _controller: YoExistoContenidoBundle:Filtro:getActividadPorArea }
    options:
        expose: true








# yoexisto_dashboard:
#     path:      /
#     defaults:  { _controller: YoExistoContenidoBundle:Default:dashboard }

yoexisto_home:
    path:      /
    defaults:  { _controller: YoExistoContenidoBundle:Default:login }


# Esto es para las 3 pantallas
yoexisto_reciente:
    path:      /reciente
    defaults:  { _controller: YoExistoContenidoBundle:Default:reciente }

yoexisto_donde:
    path:      /donde
    defaults:  { _controller: YoExistoContenidoBundle:Default:donde }

yoexisto_que:
    path:      /que
    defaults:  { _controller: YoExistoContenidoBundle:Default:que }

yoexisto_resumen:
    path:      /resumen
    defaults:  { _controller: YoExistoContenidoBundle:Default:resumen }

yoexisto_generado:
    path:      /generado
    defaults:  { _controller: YoExistoContenidoBundle:Default:generado }


yoexisto_reporte_detalle:
    path:      /reportedetalles
    defaults:  { _controller: YoExistoContenidoBundle:Default:getDetalleReporte }
    options:
        expose: true


login_check:
    path:      /login_check




salir:
    path:   /logout